from typing import Annotated, Dict
from typing_extensions import TypedDict
from langgraph.graph import MessagesState


# Researcher team state
# 使用 researcher_histories Dict 替代硬编码的 bull_history/bear_history
# 支持动态数量的 researcher（巴菲特、木头姐、彼得林奇等）
class InvestDebateState(TypedDict):
    researcher_histories: Annotated[
        Dict[str, str], "Per-researcher conversation histories, keyed by researcher_type"
    ]  # 每个研究员的独立历史记录
    history: Annotated[str, "Conversation history"]  # 全局辩论历史
    current_response: Annotated[str, "Latest response"]  # 最新响应
    judge_decision: Annotated[str, "Final judge decision"]  # 裁判决定
    latest_speaker: Annotated[str, "Researcher that spoke last"]  # 最后发言者
    count: Annotated[int, "Length of the current conversation"]  # 对话轮次


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    candlestick_report: Annotated[str, "Report from the Candlestick Analyst"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
