"""
Prompt模板子模块
===============
按职能拆分的提示词模板系统。

子模块:
- base_templates: 基础模板（身份、要求、输出格式）
- perspectives: 角色视角定义（Bull/Bear/Aggressive/Conservative/Neutral）
"""

from .base_templates import (
    EXPERT_IDENTITY_ZH,
    EXPERT_IDENTITY_EN,
    RESEARCHER_BASE_REQUIREMENTS_ZH,
    RESEARCHER_BASE_REQUIREMENTS_EN,
    RESEARCHER_OUTPUT_FORMAT_ZH,
    RESEARCHER_OUTPUT_FORMAT_EN,
    RISK_ANALYST_BASE_REQUIREMENTS_ZH,
    RISK_ANALYST_BASE_REQUIREMENTS_EN,
    RISK_ANALYST_OUTPUT_FORMAT_ZH,
    RISK_ANALYST_OUTPUT_FORMAT_EN,
)

from .perspectives import (
    BULL_PERSPECTIVE_ZH,
    BEAR_PERSPECTIVE_ZH,
    AGGRESSIVE_PERSPECTIVE_ZH,
    CONSERVATIVE_PERSPECTIVE_ZH,
    NEUTRAL_PERSPECTIVE_ZH,
)

__all__ = [
    # 基础模板
    "EXPERT_IDENTITY_ZH",
    "EXPERT_IDENTITY_EN",
    "RESEARCHER_BASE_REQUIREMENTS_ZH",
    "RESEARCHER_BASE_REQUIREMENTS_EN",
    "RESEARCHER_OUTPUT_FORMAT_ZH",
    "RESEARCHER_OUTPUT_FORMAT_EN",
    "RISK_ANALYST_BASE_REQUIREMENTS_ZH",
    "RISK_ANALYST_BASE_REQUIREMENTS_EN",
    "RISK_ANALYST_OUTPUT_FORMAT_ZH",
    "RISK_ANALYST_OUTPUT_FORMAT_EN",
    # 角色视角
    "BULL_PERSPECTIVE_ZH",
    "BEAR_PERSPECTIVE_ZH",
    "AGGRESSIVE_PERSPECTIVE_ZH",
    "CONSERVATIVE_PERSPECTIVE_ZH",
    "NEUTRAL_PERSPECTIVE_ZH",
]
